# Generated by Django 3.2.4 on 2021-08-12 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of author')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name of author')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of book')),
                ('publish_date', models.DateField(verbose_name='date of publishing')),
                ('authors', models.ManyToManyField(related_name='books', to='book.Author')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of city')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of genre')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of reader')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name of reader')),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Цена')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prices', to='book.book')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operations', to='book.reader')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(verbose_name='Номер читательского билета')),
                ('password', models.CharField(max_length=4, verbose_name='card password')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cards', to='book.reader')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', to='book.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='operations',
            field=models.ManyToManyField(related_name='books', to='book.Operation'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='name of street')),
                ('house', models.CharField(max_length=10, verbose_name='number of house')),
                ('apartment', models.CharField(default=None, max_length=10, verbose_name='number of apartment')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='book.city')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='book.reader')),
            ],
        ),
    ]
